'use client';

import React from 'react';

export default function WebsitesService() {
  return (
    <main className="min-h-screen bg-black text-white overflow-hidden">
      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 border-b border-white/10 bg-black/80 backdrop-blur-md">
        <div className="max-w-7xl mx-auto px-6 py-5 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 bg-gradient-to-br from-blue-500 to-purple-600 rounded-xl flex items-center justify-center text-white font-bold text-xl">T</div>
            <span className="font-semibold text-2xl tracking-tight">TechTenX</span>
          </div>
          <div className="hidden md:flex items-center gap-8 text-sm">
            <a href="/#services" className="hover:text-blue-400">Services</a>
            <a href="/pricing" className="hover:text-blue-400">Pricing</a>
          </div>
          <a href="/contact" className="px-6 py-2.5 bg-white text-black font-medium rounded-full hover:bg-white/90">Get Started</a>
        </div>
      </nav>

      {/* Hero */}
      <section className="pt-32 pb-16 px-6">
        <div className="max-w-4xl mx-auto text-center">
          <h1 className="text-5xl md:text-6xl font-bold tracking-tighter mb-6">AI-Powered Websites</h1>
          <p className="text-xl text-gray-400 mb-8">Beautiful, fast websites. Generated by AI or custom-built. Deployed instantly.</p>
          <a href="/pricing" className="inline-block px-8 py-4 bg-gradient-to-r from-blue-600 to-purple-600 rounded-2xl font-semibold">Build Your Site</a>
        </div>
      </section>

      {/* What It Is */}
      <section className="px-6 py-20 bg-zinc-950 border-t border-white/10">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-4xl font-semibold mb-8">Three Ways to Build</h2>
          <p className="text-gray-400 text-lg mb-12">Choose the method that fits your needs.</p>
          <div className="grid md:grid-cols-3 gap-6">
            <div className="bg-zinc-900 p-6 rounded-2xl border border-white/10">
              <h3 className="text-xl font-semibold mb-3">🤖 AI Generated</h3>
              <p className="text-gray-400 mb-4">Describe your site in a prompt. AI builds it in seconds.</p>
              <p className="text-sm text-blue-400">Start: $29/mo</p>
            </div>
            <div className="bg-zinc-900 p-6 rounded-2xl border border-white/10">
              <h3 className="text-xl font-semibold mb-3">✨ Template</h3>
              <p className="text-gray-400 mb-4">Choose from 100+ templates. Customize with drag & drop.</p>
              <p className="text-sm text-blue-400">Start: $29/mo</p>
            </div>
            <div className="bg-zinc-900 p-6 rounded-2xl border border-white/10">
              <h3 className="text-xl font-semibold mb-3">💻 Custom Dev</h3>
              <p className="text-gray-400 mb-4">Our team builds exactly what you need.</p>
              <p className="text-sm text-blue-400">Enterprise</p>
            </div>
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="px-6 py-20">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-4xl font-semibold mb-16 text-center">How It Works</h2>
          <div className="space-y-8">
            <div className="flex gap-8">
              <div className="flex-shrink-0">
                <div className="flex h-12 w-12 items-center justify-center rounded-full bg-blue-600 font-bold">1</div>
              </div>
              <div>
                <h3 className="text-2xl font-semibold mb-2">Describe Your Vision</h3>
                <p className="text-gray-400">Tell us what your site should look like, what it does, your goals.</p>
              </div>
            </div>
            <div className="flex gap-8">
              <div className="flex-shrink-0">
                <div className="flex h-12 w-12 items-center justify-center rounded-full bg-blue-600 font-bold">2</div>
              </div>
              <div>
                <h3 className="text-2xl font-semibold mb-2">AI Generates Site</h3>
                <p className="text-gray-400">Our AI builds a beautiful, SEO-optimized site in minutes.</p>
              </div>
            </div>
            <div className="flex gap-8">
              <div className="flex-shrink-0">
                <div className="flex h-12 w-12 items-center justify-center rounded-full bg-blue-600 font-bold">3</div>
              </div>
              <div>
                <h3 className="text-2xl font-semibold mb-2">Customize & Deploy</h3>
                <p className="text-gray-400">Make tweaks, add content, then deploy. Your site is live immediately.</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="px-6 py-20 bg-zinc-950 border-t border-white/10">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-4xl font-semibold mb-16 text-center">Included Features</h2>
          <div className="grid md:grid-cols-2 gap-6">
            <div className="flex items-start gap-3">
              <span className="text-blue-400 text-xl">✓</span>
              <div>
                <h3 className="font-semibold mb-1">Mobile Responsive</h3>
                <p className="text-gray-400 text-sm">Looks perfect on all devices</p>
              </div>
            </div>
            <div className="flex items-start gap-3">
              <span className="text-blue-400 text-xl">✓</span>
              <div>
                <h3 className="font-semibold mb-1">SEO Optimized</h3>
                <p className="text-gray-400 text-sm">Rank higher on Google</p>
              </div>
            </div>
            <div className="flex items-start gap-3">
              <span className="text-blue-400 text-xl">✓</span>
              <div>
                <h3 className="font-semibold mb-1">AI Analytics</h3>
                <p className="text-gray-400 text-sm">Track visitor behavior with AI insights</p>
              </div>
            </div>
            <div className="flex items-start gap-3">
              <span className="text-blue-400 text-xl">✓</span>
              <div>
                <h3 className="font-semibold mb-1">E-Commerce Ready</h3>
                <p className="text-gray-400 text-sm">Built-in payment processing</p>
              </div>
            </div>
            <div className="flex items-start gap-3">
              <span className="text-blue-400 text-xl">✓</span>
              <div>
                <h3 className="font-semibold mb-1">Custom Domain</h3>
                <p className="text-gray-400 text-sm">Use your own domain name</p>
              </div>
            </div>
            <div className="flex items-start gap-3">
              <span className="text-blue-400 text-xl">✓</span>
              <div>
                <h3 className="font-semibold mb-1">AI Chatbot</h3>
                <p className="text-gray-400 text-sm">Customer support agent included</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="px-6 py-20">
        <div className="max-w-3xl mx-auto">
          <h2 className="text-4xl font-semibold mb-12 text-center">FAQ</h2>
          <div className="space-y-6">
            <div className="border-b border-white/10 pb-6">
              <h3 className="text-xl font-semibold mb-3 text-blue-400">Can I own my site?</h3>
              <p className="text-gray-400">Yes. Your site, your data, your domain. You can download it anytime.</p>
            </div>
            <div className="border-b border-white/10 pb-6">
              <h3 className="text-xl font-semibold mb-3 text-blue-400">Is it fast?</h3>
              <p className="text-gray-400">Very. Our sites average <1s load time. Globally distributed CDN included.</p>
            </div>
            <div className="pb-6">
              <h3 className="text-xl font-semibold mb-3 text-blue-400">Can I migrate from another builder?</h3>
              <p className="text-gray-400">Yes. We help migrate content from Wix, Squarespace, WordPress, etc. Enterprise support included.</p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="px-6 py-20 border-t border-white/10">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-4xl font-semibold mb-8">Ready to Launch Your Site?</h2>
          <a href="/pricing" className="inline-block px-10 py-4 bg-gradient-to-r from-blue-600 to-purple-600 rounded-2xl font-semibold hover:scale-105">Start Free</a>
        </div>
      </section>

      <footer className="py-12 border-t border-white/10 text-center text-sm text-gray-500">© 2026 TechTenX.</footer>
    </main>
  );
}
